<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_author-details',
		'title' => 'Author Details',
		'fields' => array (
			array (
				'key' => 'field_51fe0fa70b10a',
				'label' => 'Author Photo',
				'name' => 'author_photo',
				'type' => 'image',
				'instructions' => 'Upload an author display picture',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_user',
					'operator' => '==',
					'value' => 'all',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_event-options',
		'title' => 'Event Options',
		'fields' => array (
			array (
				'key' => 'field_52a6f18f80bc0',
				'label' => 'Event Type',
				'name' => 'event_type',
				'type' => 'radio',
				'instructions' => 'Select an event type:
	<b>Single Event:</b>, it\'s what it sounds like. A single event on a single event page. Non recurring basically, would be good for large events.
	<b>Grouped Events:</b> these events are a bunch you want to show on a single page. This would be good for something like MIFF, or even a week of screenings.',
				'required' => 1,
				'choices' => array (
					'singleevent' => 'Single Event',
					'groupedevent' => 'Grouped Event',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'singleevent',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_52a6f28b87895',
				'label' => 'Event Location',
				'name' => 'event_location',
				'type' => 'location-field',
				'instructions' => 'Choose the event location',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52a6f18f80bc0',
							'operator' => '==',
							'value' => 'singleevent',
						),
					),
					'allorany' => 'all',
				),
				'val' => 'address',
				'mapheight' => 300,
				'center' => '48.856614,2.3522219000000177',
				'zoom' => 10,
				'scrollwheel' => 1,
				'mapTypeControl' => 0,
				'streetViewControl' => 1,
				'PointOfInterest' => 0,
			),
			array (
				'key' => 'field_52a6f3d5878a0',
				'label' => 'Event Time',
				'name' => 'event_time',
				'type' => 'number',
				'instructions' => '24 Hour time please! We\'ll convert it to AM / PM on the frontend.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52a6f18f80bc0',
							'operator' => '==',
							'value' => 'singleevent',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_52a6f2ab87896',
				'label' => 'Event Start Date',
				'name' => 'event_start_date',
				'type' => 'date_picker',
				'instructions' => 'Choose the start date',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52a6f18f80bc0',
							'operator' => '==',
							'value' => 'singleevent',
						),
					),
					'allorany' => 'all',
				),
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_52a6f2d487897',
				'label' => 'Event End Date',
				'name' => 'event_end_date',
				'type' => 'date_picker',
				'instructions' => 'Choose the end date, if single day event you can leave blank.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52a6f18f80bc0',
							'operator' => '==',
							'value' => 'singleevent',
						),
					),
					'allorany' => 'all',
				),
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_52a6f5b5bdc20',
				'label' => 'Event Link',
				'name' => 'event_link',
				'type' => 'text',
				'instructions' => 'Input the event link, no http://www needed.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52a6f18f80bc0',
							'operator' => '==',
							'value' => 'singleevent',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'http://www.',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a6f4e45e972',
				'label' => 'Connected to a festival?',
				'name' => 'festival_connection',
				'type' => 'taxonomy',
				'instructions' => 'If this post is connected to a festival please select the festival from the categories',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52a6f18f80bc0',
							'operator' => '==',
							'value' => 'singleevent',
						),
					),
					'allorany' => 'all',
				),
				'taxonomy' => 'category',
				'field_type' => 'checkbox',
				'allow_null' => 1,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_52a6f30787898',
				'label' => 'Grouped Events',
				'name' => 'grouped_events',
				'type' => 'flexible_content',
				'instructions' => 'Add grouped events!',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52a6f18f80bc0',
							'operator' => '==',
							'value' => 'groupedevent',
						),
					),
					'allorany' => 'all',
				),
				'layouts' => array (
					array (
						'label' => 'Normal Event',
						'name' => 'normal_event',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_52a6f33f87899',
								'label' => 'Event Name',
								'name' => 'event_name',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_52a6f3588789b',
								'label' => 'Event Writeup',
								'name' => 'event_writeup',
								'type' => 'textarea',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'formatting' => 'br',
							),
							array (
								'key' => 'field_52a6f3608789c',
								'label' => 'Event Image',
								'name' => 'event_image',
								'type' => 'image',
								'instructions' => 'Add an image if you have one.',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_52a6f34c8789a',
								'label' => 'Event Location',
								'name' => 'event_location',
								'type' => 'location-field',
								'column_width' => '',
								'val' => 'address',
								'mapheight' => 300,
								'center' => '48.856614,2.3522219000000177',
								'zoom' => 10,
								'scrollwheel' => 1,
								'mapTypeControl' => 1,
								'streetViewControl' => 1,
								'PointOfInterest' => 1,
							),
							array (
								'key' => 'field_52a6f37a8789d',
								'label' => 'Event Start Date',
								'name' => 'event_start_date',
								'type' => 'date_picker',
								'column_width' => '',
								'date_format' => 'yymmdd',
								'display_format' => 'dd/mm/yy',
								'first_day' => 1,
							),
							array (
								'key' => 'field_52a6f38b8789e',
								'label' => 'Event End Date',
								'name' => 'event_end_date',
								'type' => 'date_picker',
								'instructions' => 'You can leave blank if the same as start',
								'column_width' => '',
								'date_format' => 'yymmdd',
								'display_format' => 'dd/mm/yy',
								'first_day' => 1,
							),
							array (
								'key' => 'field_52a6f39e8789f',
								'label' => 'Event Time',
								'name' => 'event_time',
								'type' => 'number',
								'instructions' => '24 hour time please!! We\'ll convert it to AM/PM on the frontend.',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array (
								'key' => 'field_52a6f5d2bdc21',
								'label' => 'Event Link',
								'name' => 'event_link',
								'type' => 'text',
								'instructions' => 'No http://www. needed',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'http://www.',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_52a6f5225e973',
								'label' => 'Connected to a festival?',
								'name' => 'festival_connection',
								'type' => 'taxonomy',
								'instructions' => 'If connected to a fest, select it here',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'checkbox',
								'allow_null' => 1,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
						),
					),
				),
				'button_label' => 'Add Event',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'events',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_options-panel',
		'title' => 'Options Panel',
		'fields' => array (
			array (
				'key' => 'field_51fc966ddcb13',
				'label' => 'Homepage Options',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_51fc967adcb14',
				'label' => 'Slider Posts',
				'name' => 'slider_posts',
				'type' => 'relationship',
				'instructions' => 'Choose the posts / events to sit in the slider on the homepage',
				'post_type' => array (
					0 => 'post',
					1 => 'events',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
					1 => 'post_type',
				),
				'result_elements' => array (
					0 => 'post_type',
					1 => 'post_title',
				),
				'max' => 4,
				'return_format' => 'object',
			),
			array (
				'key' => 'field_51fe0c67db925',
				'label' => 'Featured Posts',
				'name' => 'featured_posts',
				'type' => 'repeater',
				'instructions' => 'Choose the featured post for each category',
				'sub_fields' => array (
					array (
						'key' => 'field_51fe0c7cdb926',
						'label' => 'Category Slug',
						'name' => 'category_slug',
						'type' => 'text',
						'instructions' => 'Input the category slug',
						'column_width' => '',
						'default_value' => '',
						'formatting' => 'html',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array (
						'key' => 'field_51fe0c86db927',
						'label' => 'Featured Post',
						'name' => 'featured_post',
						'type' => 'relationship',
						'instructions' => 'Choose the featured Post, if no featured post put together the featured below.',
						'column_width' => '',
						'post_type' => array (
							0 => 'post',
							1 => 'page',
							2 => 'events',
						),
						'taxonomy' => array (
							0 => 'all',
						),
						'filters' => array (
							0 => 'search',
						),
						'result_elements' => array (
							0 => 'post_type',
							1 => 'post_title',
						),
						'max' => '',
						'return_format' => 'object',
					),
					array (
						'key' => 'field_51fe0d19db928',
						'label' => 'Title',
						'name' => 'feat_title',
						'type' => 'text',
						'instructions' => 'If no featured post has been selected, set the title',
						'column_width' => '',
						'default_value' => '',
						'formatting' => 'html',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array (
						'key' => 'field_51fe0d2fdb929',
						'label' => 'Message',
						'name' => 'feat_message',
						'type' => 'textarea',
						'instructions' => 'If no featured post, add a message',
						'column_width' => '',
						'default_value' => '',
						'formatting' => 'br',
						'maxlength' => '',
						'placeholder' => '',
					),
					array (
						'key' => 'field_51fe0d45db92a',
						'label' => 'Image',
						'name' => 'feat_image',
						'type' => 'image',
						'instructions' => 'If no featured post, add the featured image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
				),
				'row_min' => 0,
				'row_limit' => 12,
				'layout' => 'row',
				'button_label' => 'Add Featured Panel',
			),
			array (
				'key' => 'field_51fe02981832e',
				'label' => 'General Site Options',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_51fe02a21832f',
				'label' => 'Mailchimp embed code',
				'name' => 'MC_embed',
				'type' => 'textarea',
				'instructions' => 'Input the short mailchimp embed code here.',
				'default_value' => '',
				'formatting' => 'html',
				'maxlength' => '',
				'placeholder' => '',
			),
			array (
				'key' => 'field_51fe03c6405f9',
				'label' => 'Mailchimp call to actions',
				'name' => 'MC_cta',
				'type' => 'repeater',
				'instructions' => 'Add multiple call to actions to this signup form along with their IDs.',
				'sub_fields' => array (
					array (
						'key' => 'field_51fe0426405fc',
						'label' => 'Call to action ID',
						'name' => 'cta_ID',
						'type' => 'text',
						'instructions' => 'ID must be unique',
						'column_width' => '',
						'default_value' => '',
						'formatting' => 'html',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array (
						'key' => 'field_51fe043d405fd',
						'label' => 'Call to action title',
						'name' => 'cta_title',
						'type' => 'text',
						'instructions' => 'Add a title for this call to action',
						'column_width' => '',
						'default_value' => '',
						'formatting' => 'html',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array (
						'key' => 'field_51fe0452405fe',
						'label' => 'Call to action message',
						'name' => 'cta_message',
						'type' => 'textarea',
						'column_width' => '',
						'default_value' => '',
						'formatting' => 'br',
						'maxlength' => '',
						'placeholder' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => 4,
				'layout' => 'table',
				'button_label' => 'Add form message',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_post-options',
		'title' => 'Post Options',
		'fields' => array (
			array (
				'key' => 'field_52926e2ec5365',
				'label' => 'Brief post description',
				'name' => 'brief_post_description',
				'type' => 'textarea',
				'instructions' => 'Input a short overview of the post',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_51f6514046f5e',
				'label' => 'Important post details',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_51f6514b46f5f',
				'label' => 'message',
				'name' => '',
				'type' => 'message',
				'message' => 'It\'s important you input all of the data in this tab as we use it across the site and in promotion for this post. If your post is missing this information you may miss out on being featured.',
			),
			array (
				'key' => 'field_51f650c5d82a7',
				'label' => 'Featured Image',
				'name' => 'featured_wide',
				'type' => 'image',
				'instructions' => 'Add a featured image for this post. Ideal width is 1000px but if you stretch over this we\'ll be awesome and resize it for you. Please don\'t undershoot this value though or your post will look bad.',
				'save_format' => 'object',
				'preview_size' => 'large',
				'library' => 'all',
			),
			array (
				'key' => 'field_51f8d33c1add9',
				'label' => 'Small Feature Image',
				'name' => 'small_feature_image',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_51f650f1d82a8',
				'label' => 'Voting',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_51f8d3071add8',
				'label' => 'Film Title',
				'name' => 'film_title',
				'type' => 'text',
				'instructions' => 'Please input the film title this article is about, if there\'s multiple films input the best one....or whichever you would like associated with this post. This is used in the API to generate awesome shit.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_51f65103d82a9',
				'label' => 'Number of Votes',
				'name' => 'post_votes',
				'type' => 'number',
				'instructions' => 'Total number of votes',
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => '',
				'step' => 1,
			),
			array (
				'key' => 'field_51f6512146f5d',
				'label' => 'Positive Votes',
				'name' => 'post_positives',
				'type' => 'number',
				'instructions' => 'Number of positive votes',
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => '',
				'step' => 1,
			),
			array (
				'key' => 'field_51f8d2ba69686',
				'label' => 'Admin Options',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_51f8d2c869687',
				'label' => 'Reading Time (minutes)',
				'name' => 'minutes_read',
				'type' => 'number',
				'instructions' => 'Input how long this article took to read',
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => '',
				'step' => 1,
			),
			array (
				'key' => 'field_52926ee4504f8',
				'label' => 'Stars',
				'name' => 'stars',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => 'How many stars would you give this film out of 10?',
				'prepend' => '',
				'append' => '/10',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_multi-page-post',
		'title' => 'Multi Page Post',
		'fields' => array (
			array (
				'key' => 'field_52a04a411e713',
				'label' => 'Items per page',
				'name' => 'items_per_page',
				'type' => 'number',
				'instructions' => 'Choose how many items you would like per page',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_52a04a081e711',
				'label' => 'Multi Page Module',
				'name' => 'multi_page_post',
				'type' => 'repeater',
				'instructions' => 'Click add page to create a multi page module',
				'sub_fields' => array (
					array (
						'key' => 'field_52a04a361e712',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_52a04a5c1e714',
						'label' => 'Content',
						'name' => 'content',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Page',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
?>